### ISSUE TITLE
Make the transform method actually change the frame of the view!

### ISSUE THREAD

**Issue by Sweeper777** [rchatham/Animate#6]
I first performed this animation:

    var moveUp: Animate {
        return transform(duration: 0.5, transforms: [
            .move(x: 0, y: -100)
            ])
    }

Then I performed this:

    var moveRight: Animate {
        return transform(duration: SquareView.animDuration, transforms: [
            .move(x: 100, y: 0)
            ])
    }

The view moves up, then to the bottom right. I have expected it to move the view up, then straight to the right i.e. equivalent to moving `(x: 100, y: -100)`.

I think this happens because when I do the second animation, the view thinks it is still at its original position, before the first animation.

Can the transform method _actually_ move the view?

**Comment by rchatham** [comment]
The Apple api that these methods cover, `CGAffineTransform`, currently doesn't support that for view transformations. The frame always remains the same. For now you can do frame transformations like you normally would using: `Animate(duration: TimeInteval, animationBlock: @escaping AnimationBlock)`. Try these extensions for now and I will consider renaming. This could potentially break people's code so it will have to go in a larger release.
```
extension UIView {
    func moveUp(duration: TimeInterval) -> Animate {
        return Animate(duration: duration) {
            self.frame.origin = CGPoint(x: self.frame.origin.x, y: self.frame.origin.y - 100)
        }
    }
    
    func moveRight(duration: TimeInterval) -> Animate {
        return Animate(duration: duration) {
            self.frame.origin = CGPoint(x: self.frame.origin.x + 100, y: self.frame.origin.y)
        }
    }
    
    func moveDown(duration: TimeInterval) -> Animate {
        return Animate(duration: duration) {
            self.frame.origin = CGPoint(x: self.frame.origin.x, y: self.frame.origin.y + 100)
        }
    }
    
    func moveLeft(duration: TimeInterval) -> Animate {
        return Animate(duration: duration) {
            self.frame.origin = CGPoint(x: self.frame.origin.x - 100, y: self.frame.origin.y)
        }
    }
}
```

**Comment by Sweeper777** [comment]
Ok,I see. Yhank you!
