### ISSUE TITLE
How do I remove the view from super view after a disappear animation?

### ISSUE THREAD

**Issue by Sweeper777** [rchatham/Animate#7]
transform(duration: 0.5, transforms: [
            .scale(x: 0, y: 0)
            ]).do { [weak self] in
                self?.removeFromSuperview()
        }

I have the above animation. I was hoping that when performed, the view will shrink and after 0.5 seconds it will be removed from the super view. However, it actually just make the view disappear without the animation. I thought the `do` block will run code after the animations. Am i misunderstanding this? How can I remove the view from super view after animation finishes?

**Comment by rchatham** [comment]
You can call `removeFormSuperview` in the completion block when you call perform. Will that work for your use case?

**Comment by Sweeper777** [comment]
I think that should work. However, I want to write the removeFromSuperview call in the view class, so the VC, who is performing the animation, doesn't need to worry about that. Is there any way to do this?

**Comment by rchatham** [comment]
I believe your assumption above in your original comment should work. Is this not happening correctly? You may need to call `layoutIfNeeded()` again to get the vc to show that the view has been removed.

**Comment by Sweeper777** [comment]
Actually I just found out that doing a scale animation of (0,0) will just make the view disappear immediately. This made it seem like the view is removed before the animation finishes. I changed both x and y to 0.1 and it works.

**Comment by rchatham** [comment]
Awesome! This is good info. Thanks for the update.
